language: cpp
compiler: clang
addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - python3
        - libstdc++-4.8-dev
install: true
before_install:
 - chmod +x critic
pip install -I pexpect
script: ./critic test
